# Generated by Django 3.0.2 on 2020-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('father', models.CharField(max_length=50, verbose_name='отчество')),
                ('class_letter', models.CharField(max_length=50, verbose_name='класс')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('date', models.DateTimeField(verbose_name='дата заявки')),
            ],
        ),
    ]
