# Generated by Django 3.0.2 on 2020-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информацию об ученике', 'verbose_name_plural': 'Информация об ученике'},
        ),
        migrations.AddField(
            model_name='info',
            name='confirmation',
            field=models.IntegerField(default=0, verbose_name='подтверждение'),
        ),
    ]
