# Generated by Django 3.0.2 on 2020-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200131_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название школы')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта секретаря')),
            ],
            options={
                'verbose_name': 'Информацию о школе',
                'verbose_name_plural': 'Информация о школе',
            },
        ),
    ]
