# Generated by Django 3.0.2 on 2020-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='schools',
            field=models.CharField(default='НЕИЗВЕСТНО', max_length=50, verbose_name='школа'),
        ),
    ]
