# Generated by Django 3.0.2 on 2020-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_info_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='confirmation',
            field=models.IntegerField(default=0, verbose_name='потверждение'),
        ),
    ]
