# Generated by Django 3.0.2 on 2020-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200226_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='name_in_english',
            field=models.CharField(default='НЕИЗВЕСТНО', max_length=50, verbose_name='Название школы на английской языке'),
        ),
    ]
